# $authToken =
# GET http://localhost/api/auth/token
# Content-Type: application/json

# {
#   "login": "some",
#   "password": "asdfasdfasdf",
# }

# GET http://localhost/api/clients
# Authorization: $authToken

# GET http://localhost/api/products
# Authorization: $authToken

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "TrietHuynh",
    "password": "$2a$10$WvTPahjgOYDBrW//ByL8jusfFWd7ETLailSuZMycygQifmCih7kgi"
}
### Token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzIxNjYzNzY2LCJleHAiOjE3MjE3NTAxNjZ9.aDKCtUMSf4kL4sM9h1P_jYWVCjtgO6HXzSYaTPsqNvU
### Get User Infor
GET http://localhost:3000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzIxNjYzNzY2LCJleHAiOjE3MjE3NTAxNjZ9.aDKCtUMSf4kL4sM9h1P_jYWVCjtgO6HXzSYaTPsqNvU

### Get Player Data + Reward
GET http://localhost:3000/api/user/player
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzIxNjYzNzY2LCJleHAiOjE3MjE3NTAxNjZ9.aDKCtUMSf4kL4sM9h1P_jYWVCjtgO6HXzSYaTPsqNvU



######## User Map
GET http://localhost:3000/api/user/map
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzIxNjU3MzYzLCJleHAiOjE3MjE3NDM3NjN9.7MonsyhPrqNHiU0bbXpSCoihaV4fNUZQde-qor2LVpc

###
GET http://localhost:3000/api/user/map/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzIxODY0MDY3LCJleHAiOjE3MjE5NTA0Njd9.VwPJJsg3O36E_AID6k4Eo4RlbgDeFL0qeT3CeIkXv10

######## Map
GET http://localhost:3000/api/map

###
GET http://localhost:3000/api/map/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzIxNjYzNzY2LCJleHAiOjE3MjE3NTAxNjZ9.aDKCtUMSf4kL4sM9h1P_jYWVCjtgO6HXzSYaTPsqNvU

###
GET http://localhost:3000/api/map/1

### 9: no active
GET http://localhost:3000/api/map/9