# $authToken =
# GET http://localhost/api/auth/token
# Content-Type: application/json

# {
#   "login": "some",
#   "password": "asdfasdfasdf",
# }

# GET http://localhost/api/clients
# Authorization: $authToken

# GET http://localhost/api/products
# Authorization: $authToken

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "TrietHuynh",
    "password": "c+qOaBlxvL59hjs92YClUH1/Lpmfi7q5U/QFByPX326dJbAfT/3Ee25x0n4/rbwj4ADibI8zH66ObZfHzOJdgQ=="
}
### Token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzIxNjYzNzY2LCJleHAiOjE3MjE3NTAxNjZ9.aDKCtUMSf4kL4sM9h1P_jYWVCjtgO6HXzSYaTPsqNvU
### Get User Infor
GET http://localhost:3000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzIxODY4MzEzLCJleHAiOjE3MjE5NTQ3MTN9.9ukToCd1lP9l066L2G-0kIrtVrfpWG3ieolePmmqHCk

### Get Player Data + Reward
GET http://localhost:3000/api/user/player
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzIxODY4MzEzLCJleHAiOjE3MjE5NTQ3MTN9.9ukToCd1lP9l066L2G-0kIrtVrfpWG3ieolePmmqHCk

######## Map
GET http://localhost:3000/api/object/map

###
GET http://localhost:3000/api/object/1

###
GET http://localhost:3000/api/object/1/children

### 9: no active
GET http://localhost:3000/api/object/9


########### Land
GET http://localhost:3000/api/land/5


######## User Map
GET http://localhost:3000/api/user/map
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzIyMjYxMDY0LCJleHAiOjE3MjIzNDc0NjR9.40eK-5ImSJsTm-7e79dReIKBnX0tSlvA_koGG44_g9g

###
GET http://localhost:3000/api/user/map/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzIyMjYxMDY0LCJleHAiOjE3MjIzNDc0NjR9.40eK-5ImSJsTm-7e79dReIKBnX0tSlvA_koGG44_g9g

######## User Land
GET http://localhost:3000/api/user/map/1/land
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzIyMjYxMDY0LCJleHAiOjE3MjIzNDc0NjR9.40eK-5ImSJsTm-7e79dReIKBnX0tSlvA_koGG44_g9g

###
GET http://localhost:3000/api/user/map/1/land/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzIyMjYxMDY0LCJleHAiOjE3MjIzNDc0NjR9.40eK-5ImSJsTm-7e79dReIKBnX0tSlvA_koGG44_g9g

######## User Checkpoint
GET http://localhost:3000/api/user/map/1/land/2/checkpoint
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzIyMjYxMDY0LCJleHAiOjE3MjIzNDc0NjR9.40eK-5ImSJsTm-7e79dReIKBnX0tSlvA_koGG44_g9g

###
GET http://localhost:3000/api/user/map/1/land/2/checkpoint/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzIyMjYxMDY0LCJleHAiOjE3MjIzNDc0NjR9.40eK-5ImSJsTm-7e79dReIKBnX0tSlvA_koGG44_g9g


########### RESULT
### Checkpoint
POST http://localhost:3000/api/user/result/checkpoint/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzIyMDIyNzc2LCJleHAiOjE3MjIxMDkxNzZ9.3CaLwYumDVcwOTDIkx3SNob5cqXfJjs3cRPCJbLZZY0

{
    "checkpointId": 6,
    "score": 100
}

### land
POST http://localhost:3000/api/user/result/land/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzIyMDIyNzc2LCJleHAiOjE3MjIxMDkxNzZ9.3CaLwYumDVcwOTDIkx3SNob5cqXfJjs3cRPCJbLZZY0

{
    "landId": 2,
    "score": 1000
}

### map
POST http://localhost:3000/api/user/result/map/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzIyMDIyNzc2LCJleHAiOjE3MjIxMDkxNzZ9.3CaLwYumDVcwOTDIkx3SNob5cqXfJjs3cRPCJbLZZY0

{
    "mapId": 1,
    "score": 100000
}

### game
POST http://localhost:3000/api/user/result/game/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzIyMDIyNzc2LCJleHAiOjE3MjIxMDkxNzZ9.3CaLwYumDVcwOTDIkx3SNob5cqXfJjs3cRPCJbLZZY0

{

}

###
GET http://localhost:3000/api/user/result/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzIyMDIyNzc2LCJleHAiOjE3MjIxMDkxNzZ9.3CaLwYumDVcwOTDIkx3SNob5cqXfJjs3cRPCJbLZZY0

###
GET http://localhost:3000/api/user/result/checkpoint
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzIyMDIyNzc2LCJleHAiOjE3MjIxMDkxNzZ9.3CaLwYumDVcwOTDIkx3SNob5cqXfJjs3cRPCJbLZZY0
